version: "3.9"

services:
  web:
    build: .
    command: gunicorn havoc.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: havocdb
      POSTGRES_USER: havocuser
      POSTGRES_PASSWORD: havocpass

volumes:
  postgres_data: