# Generated by Django 5.2.2 on 2025-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, help_text='Website do comentarista (opcional)', null=True, verbose_name='website'),
        ),
    ]
